name: CI

on:
  push:
    branches: ["main"]

jobs:
  deploy-dev:
    name: "Deploy Dev"
    runs-on: ubuntu-latest
    outputs:
      app_url: ${{ steps.get_url.outputs.URL}}

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.8.4"

      - name: Terraform Init & Apply - Dev
        run: |
          cd environment/dev
          terraform init \
          -backend-config="bucket=bucket-S3" \
          -backend-config="key=dev/terraform.tfstate" \
          -backend-config="region=us-east-1"
          terraform apply -auto-approve -var="api_key=${{ secrets.API_KEY }}"  -var="DB_PASSWORD=${{ secrets.DB_PASSWORD }}"

      - name: Get App Url
        id: get_url
        run: |
          cd environment/dev
          URL=$(terraform output -raw app_url)
          echo "URL=$URL" >> $GITHUB_OUTPUT

  health-check:
    name: "Verify Dev Health"
    needs: deploy-dev
    runs-on: ubuntu-latest
    steps:
      - name: Check URL status
        run: |
          TARGET_URL="${{ needs.deploy-dev.outputs.app_url}}"
          echo "Teste: $TARGET_URL"

          echo "O App Runner muito tempo para ligar"
          sleep 130

          curl --retry 5 --retry-delay 20 --fail "$TARGET_URL" || exit 1

  deploy-prod:
    name: "Deploy Prod"
    needs: health-check 
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: aws-actions/configure-aws-credentials@v4
         with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
            terraform_version: "1.8.4"
    
       - name: Terraform Init & Apply Prod
         run: |
            cd environment/prod
            terraform init \
            -backend-config="bucket=bucket-S3" \ 
            -backend-config="key=prod/terraform.tfstate" \
            -backend-config="region=us-east-1"
            terraform apply -auto-approve -var="api_key=${{ secrets.API_KEY }}" -var="DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
       - name: Get App Url Prod
         id: get_url_prod
         run: |
           cd environment/prod
           URL=$(terraform output -raw app_url)
           echo "URL=$URL" >> $GITHUB_OUTPUT
           echo "A URL de Produção é: $URL"
  